### ISSUE TITLE
Decide on covjson.org namespaces

### ISSUE THREAD

**Issue by neothemachine** [covjson/specification#69]
Since we have covjson.org now, we should finalize the namespace URLs that we want to use.

Some things to consider:
- We don't have SSL (not supported by github pages anyway), so let's just use http://
- We can have namespaces like http://covjson.org/def/core#, however this redirects to http://covjson.org/def/core/# due to the way these extensionless pages work (/core would actually be a folder with an index.html file, otherwise you could only have /core.html which we don't want). The question therefore is, http://covjson.org/def/core# or http://covjson.org/def/core/#. I vote for the former, even if it redirects, just because the latter is really uncommon. It's either without slash but with hash, or with slash and without hash, but never both.

What namespaces do we need?
- http://covjson.org/def/core#
- http://covjson.org/def/dataTypes# (for Primitive, Tuple, Polygon)
- http://covjson.org/def/domainTypes# (for Grid, Polygon, ...)
- http://covjson.org/def/profiles# (for standalone)

**Comment by jonblower** [comment]
Regarding the difference between core# and core/#, I really don't know. I also think that core# would follow common practice more. Maybe the SDWWG could offer advice?

That looks like a reasonable set of namespaces. How many items will there be in each namespace? I have seen small vocabularies (and even some large ones) served from a single namespace, which could possibly be refactored. There is probably a balance between logical refactoring and not having too many namespaces that could be confused.

**Comment by neothemachine** [comment]
Hmm, I guess the way we want to use it in one covjson document (where each term is unique as identifier within that document) it could make sense to group core, dataTypes, and domainTypes into a single namespace. But then that would mean that the dataTypes also have to be lowercase in their URIs which they currently are not. so there's http://covjson.org/def/dataTypes#Polygon and http://covjson.org/def/domainTypes#Polygon where the former is aliased as "polygon" in the covjson. Not sure if lowercase rdf terms are popular for non-property terms. In this case it would be the object of the subject-predicate-object triple. On the other hand, there's the primitive xsd data types which are lower case, but they are a bit different since those are the actual data types of an rdf string.

**Comment by jonblower** [comment]
Do you think that "dataTypes#Polygon" is sort of semantically equivalent to an RDF data type (e.g. "[[..][..]]"^^covjson:polygon)? If so maybe lower case is fine, and consistent with RDF practice. Not sure.

**Comment by neothemachine** [comment]
Interesting thought, given that the nested array structure for a polygon would have to be transformed to a string anyway when converting it to RDF, like a WKT encoding or similar as in GeoDCAT-AP. So from that point of view you could regard it as an RDF data type. If there's a common practice to have these lower case, probably not. I just found [rdf:PlainLiteral](https://www.w3.org/TR/rdf-plain-literal/) as a counter example. I think typically lower-case is meant for predicates.

I think a solution to this would be to group core, dataTypes, and profiles into the main namespace, and have domainTypes as separate one. I think this makes most sense since domain types are always optional and clients can still understand most of the document if they are generic enough, whereas if they don't understand a given data type, then they are lost. And introducing new data types should happen very very rarely, compared to the domain types, where the latter would then live in an open registry and will be easier to extend.

So, how about:

http://covjson.org/def/core# containing:
- Domain
- domain
- domainType
- axis
- dataType
- Primitive (can probably be omitted since it will never be explicitly included)
- Tuple
- Polygon
- num
- start
- stop
- referencing
- components (plural as it is an RDF list)
- referenceSystem
- ReferenceSystem
- CoordinateReferenceSystem
- TemporalCRS
- calendar
- timeScale
- coordinateSystemAxes (again plural being a list)
- IdentifierReferenceSystem
- targetConcept
- identifier
- Parameter
- parameter
- categoryEncoding
- ParameterGroup
- member
- range
- NdArray
- TiledNdArray
- shape (RDF list)
- tileShape (RDF list)
- axisNames (RDF list)
- urlTemplate
- tileSet   
- Coverage
- CoverageCollection
- standalone (the profile; lower-case as JSON-LD does it as well (http://www.w3.org/ns/json-ld#expanded))

http://covjson.org/def/domainTypes# containing:
- Grid
- VerticalProfile
- PointSeries
- Point
- MultiPointSeries
- MultiPoint
- Trajectory
- Section
- PolygonSeries
- Polygon
- MultiPolygonSeries
- MultiPolygon

Reused from external vocabularies:
- skos:prefLabel
- dct:title
- dct:description
- qudt:unit
- qudt:symbol
- ignf:coordinateSystem
- ignf:CoordinateSystem
- inspiregloss:TemporalReferenceSystem
- http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
- inspiregloss:SpatialReferenceSystem
- ignf:CRS
- ignf:GeodeticCRS
- ignf:ProjectedCRS
- ignf:VerticalCRS
- ignf:datum
- ignf:axisDirection
- ssn:observedProperty
- xsd:double, xsd:integer, xsd:string
- hydra:member

where...
- hydra: http://www.w3.org/ns/hydra/core#
- qudt: http://qudt.org/schema/qudt#
- ignf: http://data.ign.fr/def/ignf#
- inspiregloss: http://inspire.ec.europa.eu/glossary/
- dct: http://purl.org/dc/terms/
- skos: http://www.w3.org/2004/02/skos/core#
- ssn: http://www.w3.org/2005/Incubator/ssn/ssnx/ssn#
- xsd: http://www.w3.org/2001/XMLSchema#

**Comment by jonblower** [comment]
Yes, that plan sounds reasonable.

**Comment by neothemachine** [comment]
I was just integrating the namespaces into the JS library and found it very inconvenient to have the axis data types with different casing between the URI and JSON version. I think we should unify that so that clients can be written simpler and don't have to include those explicit mappings (but just adding one of two namespace URIs in front of the names). So, I think making the URI version lower-case as well doesn't really hurt.

**Comment by letmaik** [comment]
By the way, I found out that it *is* actually possibly to serve URLs without trailing slashes via GitHub Pages. So the namespace URLs we defined above would not need to redirect to /def/core/ from /def/core etc.
(Hint: don't use `permalink` in the frontmatter in Jekyll)
