### ISSUE TITLE
Top-level metadata for CovJSON files?

### ISSUE THREAD

**Issue by jonblower** [covjson/specification#71]
I can't remember if we've discussed this before but I wonder if it would be useful to have some slots for "top-level" metadata about a CovJSON file - e.g. contact details, author(s), publisher(s), licence(s). It occurred to me that this information would be important to display alongside the data itself.

We could argue that this information belongs in a catalogue rather than the CovJSON file, and this is still possible of course, but I tend to think that it would be good to at least provide the option to embed it. Not everyone will want to run a catalogue server, and it could be important to keep this information together with the data itself.

We might have to think about whether this should apply to all possible CovJSON documents, or just certain types (e.g. coverages and collections). Or people could just do what they want.

This kind of metadata could be quite easily expressed with JSON-LD, I should think, using existing vocabularies like Dublin Core, FOAF etc. So it could be another example of "linkiness"!

**Comment by neothemachine** [comment]
A good idea probably, considering it wouldn't have a noticeable impact on data volume, esp after gzipping.

**Comment by jonblower** [comment]
We could include some common metadata in the spec (and link to external vocabs via JSON-LD context) but also allow custom metadata via the extension mechanism you've proposed, perhaps.

**Comment by neothemachine** [comment]
We could use GeoDCAT-AP as a basis but ignore all the stuff that's strictly focused on Europe, Inspire,and string encodings of bbox'es etc.

**Comment by jonblower** [comment]
Yes. I'm thinking something like:

 * List of contacts. These are people (or organisations?) with certain optional roles, e.g. "author", "researcher", "publisher".
 * Licence. Some kind of copyright text plus link to licence text
 * High-level title and description (do we have that already?), internationalised

I can't remember what GeoDCAT-AP specifically supports or how it does it...

**Comment by letmaik** [comment]
The existing mechanism to add custom members with registered prefixes seems to cover this case. I don't think we should be prescriptive on specific kinds of metadata. I think this is again one of those things that have to evolve and hopefully a common vocabulary will be used over time for this. I think there's nothing to do here, so I'm closing this.
