### ISSUE TITLE
Create example(s) for Subsection 6.5 Coverage Collection Objects

### ISSUE THREAD

**Issue by lewismc** [covjson/specification#74]
Up until subsection [6.5 Coverage Collection Objects](https://covjson.org/spec/#coverage-collection-objects) all subsection of Section 6 contain examples. An example is absent (but would be very useful) for Subsection 6.5 Coverage Objects.

**Comment by letmaik** [comment]
Do you think the examples from the appendix are enough for both Coverage and CoveageCollection? https://covjson.org/spec/#appendix-a-coverage-examples If yes, then it's probably enough to refer to the appendix.

**Comment by lewismc** [comment]
@letmaik thanks for reply,
> Do you think the examples from the appendix are enough for both Coverage and CoveageCollection?
Yes, these examples look good. If all that is required is a markdown hyperlink to to reference the appendix then I can submit a PR.

**Comment by letmaik** [comment]
Sure, please go ahead. And thanks! :)
