### ISSUE TITLE
[DISCUSS] Google's Science Datasets documentation

### ISSUE THREAD

**Issue by lewismc** [covjson/specification#84]
Hi Folks,
I wonder if anyone saw [Google's Science Datasets](https://developers.google.com/search/docs/data-types/datasets) documentation?
If so, what are the impressions? This conversation came up recently on some W3C lists regarding making Spatial Data more discoverable by Web crawlers.

**Comment by letmaik** [comment]
I saw that, yes. I regard this the same as DCAT / GeoDCAT-AP. It is one level higher than CovJSON on the "meta" hierarchy. So you would link to CovJSON via such schema.org metadata.
Is that what you mean?

**Comment by jonblower** [comment]
I notice it has a `variableMeasured` property, which is useful (and I think is not present in GeoDCAT).

**Comment by lewismc** [comment]
@letmaik yes that is about right.

**Comment by letmaik** [comment]
I think there's nothing here related to CovJSON really, except that you link to it via [`distribution`](https://developers.google.com/search/docs/data-types/datasets#download). The only issue is that if you have a CovJSON file that is not fully self-contained (having links to remote range data) then the definition of the distribution data type [`DataDownload`](http://schema.org/DataDownload) doesn't really match as it assumes you are downloading the whole dataset in one file if I understood it correctly. I think the SDW WG mailing list is a better place to discuss that. Will close for now, but feel free to send more comments here.
