### ISSUE TITLE
Differences to OGC Coverage Implementation Schema (CIS) - not aligned with CIS 1.1

### ISSUE THREAD

**Issue by KathiSchleidt** [covjson/specification#91]
Having just read the section on Differences to OGC Coverage Implementation Schema (CIS), I'm wondering if this was really compared to CIS 1.1, or just continuing assumptions based on CIS 1.0?
Without going into details, I'd like to point out that to my understanding, the points listed under "areas where the model used by CoverageJSON departs from CIS" do NOT pertain to CIS 1.1

**Comment by jonblower** [comment]
Hi @KathiSchleidt, thanks for your comment. If I remember correctly, this was probably done with an earlier draft of CIS1.1, since I think this page was written before the final version of CIS1.1 was published. If there are errors then of course we can correct them, and apologies that we did not revisit this at the time. It's good news if there are now fewer points of departure, as it will be easier to create a mapping. Do you have time to supply more detail of where the points are wrong, please?

**Comment by KathiSchleidt** [comment]
Think it's best you take a closer look at CIS::GeneralGridCoverage. Also, maybe update the link in your text from the press statement to the standard:
https://docs.opengeospatial.org/is/09-146r6/09-146r6.html#27

To the points you make about CIS 1.1, while this is not my expertise (I come from sensor web, see the coverage stuff as an interesting alternative encoding for bulk data), here some quick feedback:
* CIS enforces exactly one coordinate reference system (CRS) per coverage, CoverageJSON allows CRSs to be associated with a given combination of coordinates.

No longer, GeneralGridCoverage allows you to pile up your axes as you like them

* CIS has separate domain concepts for grids vs other types, CoverageJSON always uses collections of orthogonal axes for organizing domains, whether gridded or not.

unclear what you mean by "grids vs other types". Up to CIS 1.0, the axes were limited to what you could set up a CRS for, 1.1 gives you indexed axes

* CIS has no specific model for describing categories of a categorical parameter, CoverageJSON defines such a model.

True - the rangeType in CIS utilizes OGC SWE Common, and one bit I miss there in the Category types is the possibility to provide the set of values that apply to the Category

* CIS has no notion of semantically grouping parameters (e.g. velocity = speed + direction), CoverageJSON allows that.

Not firm on this, but do believe the axes nests in CIS 1.1 do something like this

**Comment by jonblower** [comment]
Thank you @KathiSchleidt for kindly taking the time to add these details. We will look into this and amend the doc accordingly. I'll post back here when it's done.

**Comment by jonblower** [comment]
Just a quick update - I haven't yet had the time to look into this in a lot of detail so I've removed the offending section for now, with an intention to replace it with a more up-to-date and accurate version later

**Comment by letmaik** [comment]
This will be handled within the OGC effort: https://github.com/opengeospatial/CoverageJSON Closing this issue to avoid duplication.
