### ISSUE TITLE
Vertical Profiles - Borehole Data 

### ISSUE THREAD

**Issue by KoalaGeo** [covjson/specification#92]
Hi, 

I'm exploring the feasibility of using CoverageJSON to share geotechnical borehole data, specifically AGS data - https://www.ags.org.uk/data-format/ 

This is a text file with a collection of groups of data - see https://github.com/BritishGeologicalSurvey/pyagsapi/blob/main/test/files/example_ags.ags at it's most basic. They'd a group for the project, group for location data (there's often more than 1 borehole on a project), group for sampling/geotchnical test data, group for geology etc. 

I've had ago making a profile collection, for a project with two boreholes. However what I think I need & I'm not sure if it's valid is multiple z coordinates / irregular grid for each parameter. 

The geology data might have values lie a lithology code & a description:

- 0 m = SOIL, Grass over top brown slightly gravelly sandy clay. Sand is fine to medium, gravel is subrounded to rounded and fine to medium
- 0.3 m = MUD, Greyish brown slightly gravelly slightly sandy silty clay with medium cobble content.  Gravel is sub-angular to sub-rounded fine to coarse
- 1.0 m = CLAY, Black gravelly sandy clay
- 5 m =  SAND, Reddish brown fine to coarse sand 

A geotechnical test/sample might be like the below with multiple attributes:

- 0.5 m = 25, ES
- 0.8 m = 26, ES
- 1.11 m = 89, DS
- 1.26 m = 159, SP
- 3.45 m = 160, SD
- 4.87 m = 250, SR
- 4.90 m = 350, TO
- 5 m = 500, SO

Is having multiple z coordinates for each group the best way to do this or is there another way?

**Comment by KoalaGeo** [comment]
A real .ags file example with multiple groups - https://github.com/BritishGeologicalSurvey/pyagsapi/blob/main/test/files/real/19684.ags

**Comment by KoalaGeo** [comment]
Example code for 2 boreholes below but I still haven't got different z from each parameter. I also need to add a label & id for each borehole...

`{
    "type" : "CoverageCollection",
    "parameters" : {
      "PTIM": {
        "type" : "Parameter",
        "description" : {
          "en": "Boring/Drilling Progress by Time"
        },
        "unit" : {
          "label": {
            "en": "meters"
          },
          "symbol": {
            "value": "m",
            "type": "http://www.opengis.net/def/uom/SI/metre"
          }
        },
        "observedProperty" : {
          "label" : {
            "en": "Boring/Drilling Progress by Time"
          }
        }
      },
      "GEOL": {
        "type" : "Parameter",
        "observedProperty" : {
          "id": "https://data.bgs.ac.uk/doc/Lexicon.html",
          "label" : {
            "en": "Lexicon"
          },
          "categories": [{
            "id": "https://data.bgs.ac.uk/id/Lexicon/NamedRockUnit/H4852.html",
            "label": {
              "en": "1st Terrace Deposits (River Severn)"
            }
          }, {
            "id": "https://data.bgs.ac.uk/id/Lexicon/NamedRockUnit/S945.html",
            "label": {
              "en": "2nd Terrace Of River Cam"
            }
          }, {
            "id": "https://data.bgs.ac.uk/id/Lexicon/NamedRockUnit/TSYC.html",
            "label": {
              "en": "36 Yard Coal (West Yorkshire)"
            }
          }]
        },
        "categoryEncoding": {
          "https://data.bgs.ac.uk/id/Lexicon/NamedRockUnit/H4852.html": 0,
          "https://data.bgs.ac.uk/id/Lexicon/NamedRockUnit/S945.html": 1,
          "https://data.bgs.ac.uk/id/Lexicon/NamedRockUnit/TSYC.html": 2
        }
      }
    },
    "referencing": [{
      "coordinates": ["x","y"],
      "system": {
        "type": "GeographicCRS",
        "id": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
      }
    }, {
      "coordinates": ["z"],
      "system": {
        "type": "VerticalCRS",
        "cs": {
          "csAxes": [{
            "name": {
              "en": "Depth"
            },
            "direction": "down",
            "unit": {
              "symbol": "m"
            }
          }]
        }
      }
    }, {
      "coordinates": ["t"],
      "system": {
        "type": "TemporalRS",
        "calendar": "Gregorian"
      }
    }],
    "domainType" : "VerticalProfile",
    "coverages": [
      {
        "type" : "Coverage",
        "domain" : {
          "type": "Domain",
          "axes": {
            "x": { "values": [-10.1] },
            "y": { "values": [-40.2] },
            "z": { "values": [ 5, 8, 14 ] },
            "t": { "values": ["2013-01-13T11:12:20Z"] }
          }
        },
        "ranges" : {
          "PTIM" : {
            "type" : "NdArray",
            "dataType": "float",
            "axisNames": ["z"],
            "shape": [3],
            "values" : [ 43.7, 43.8, 43.9 ]
          },
          "GEOL" : {
            "type" : "NdArray",
            "dataType": "float",
            "axisNames": ["z"],
            "shape": [3],
            "values" : [ 0, 1, 2 ]
          }
        }
      }, {
        "type" : "Coverage",
        "domain" : {
          "type": "Domain",
          "axes": {
            "x": { "values": [-11.1] },
            "y": { "values": [-45.2] },
            "z": { "values": [ 4, 7, 9 ] },
            "t": { "values": ["2013-01-13T12:12:20Z"] }
          }
        },
        "ranges" : {
          "PTIM" : {
            "type" : "NdArray",
            "dataType": "float",
            "axisNames": ["z"],
            "shape": [3],
            "values" : [ 43.7, 43.8, 43.9 ]
          },
          "GEOL" : {
            "type" : "NdArray",
            "dataType": "float",
            "axisNames": ["z"],
            "shape": [3],
            "values" : [ 0, 1, 2 ]
          }
        }
      }]
  }`

**Comment by jonblower** [comment]
Hi @KoalaGeo - the structure of CoverageJSON is such that each Coverage has exactly one Domain (which includes the set of `z` coordinates). Each parameter (variable) in the Coverage shares the same Domain. So if you have two measurements with different sets of `z` coordinates, they will need to be in different Coverages, and you can use a CoverageCollection to group them and "factor out" common information.

I'm not 100% sure I've understood your question, but I think the structure you propose above is probably the best way to do what you want.

**Comment by letmaik** [comment]
I agree with @jonblower, but maybe I'm missing something regarding `z`.

Regarding borehole id and label, this falls outside the fields defined by CovJSON, but you can use extensions, see https://covjson.org/spec/#71-custom-members.

**Comment by KoalaGeo** [comment]
Hi Both, Thanks for those clarifications, I'll have another go

**Comment by KoalaGeo** [comment]
Think I've got it, but will need a bit more thought how this might work with multiple boreholes, guess with dct:identifier for each coverage in addition to the coverage collection

```json
{
  "type": "CoverageCollection",
	"dct:identifier": "20374782",
	"dct:hasVersion": "4.0",
	"dct:rightsHolder": "MR E. O'BRIEN",
	"dct:Location": "GLAN-Y-NANT, LLANIDLOES",
	"dct:title": "Mount Severn- Environment Agency",
	"ags:contractor:": "W.B. & A.D. MORGAN LTD.",
	"ags:engineer": "R.MILLS & J. SCOTT",
  "parameters" : {
    "PTIM": {
      "type" : "Parameter",
      "description" : {
        "en": "Boring/Drilling Progress by Time"
      },
      "unit" : {
				"label": {
					"en": "meters"
				},
				"symbol": {
					"value": "m",
					"type": "http://www.opengis.net/def/uom/SI/metre"
				}
			},
      "observedProperty" : {
        "id": "http://vocab.nerc.ac.uk/standard_name/sea_water_salinity/",
        "label" : {
          "en": "Boring/Drilling Progress by Time"
        }
      }
    },
    "GEOL": {
			"type": "Parameter",
			"observedProperty": {
				"id": "https://data.ags.org.uk/def/ags/geol",
				"label": {
					"en": "Geology"
				},
				"categories": [{
					"id": "101",
					"label": {
						"en": "Overburden"
					}
				},{
					"id": "817",
					"label": {
						"en": "Limestone Shale"
					}
				}],
      "categoryEncoding": {
					"101": 101,
					"817": 817
			}
    }
  }
  },
  "referencing": [{
    "coordinates": ["x","y"],
    "system": {
      "type": "GeographicCRS",
      "id": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
    }
  }, {
    "coordinates": ["z"],
    "system": {
      "type": "VerticalCRS",
      "cs": {
        "csAxes": [{
          "name": {
            "en": "Depth"
          },
          "direction": "down",
          "unit": {
            "symbol": "m"
          }
        }]
      }
    }
  }, {
    "coordinates": ["t"],
    "system": {
      "type": "TemporalRS",
      "calendar": "Gregorian"
    }
  }],
  "domainType" : "VerticalProfile",
  "coverages": [
    {
      "type" : "Coverage",
      "domain" : {
        "type": "Domain",
        "axes": {
          "x": { "values": [-52.4437409194] },
          "y": { "values": [-3.5550706475] },
          "z": { "values": [ 5, 8, 14 ] },
          "t": { "values": ["2013-01-13T11:12:20Z"] }
        }
      },
      "ranges" : {
        "GEOL" : {
          "type" : "NdArray",
          "dataType": "integer",
          "axisNames": ["z"],
          "shape": [3],
          "values" : [ 101, 101, 817 ]
        }
      }
    }, {
      "type" : "Coverage",
      "domain" : {
        "type": "Domain",
        "axes": {
          "x": { "values": [-52.443] },
          "y": { "values": [-3.55] },
          "z": { "values": [ 4, 7, 9 ] },
          "t": { "values": ["2013-01-13T12:12:20Z"] }
        }
      },
      "ranges" : {
        "PTIM" : {
          "type" : "NdArray",
          "dataType": "float",
          "axisNames": ["z"],
          "shape": [3],
          "values" : [ 42.7, 41.8, 40.9 ]
        }
      }
    }]
}
```
